sudo: required
services:
  - docker

before_install:
  - docker build -t satishrsdg/react-test -f ./client/Dockerfile.dev ./client

script:
  # ensures npm test exits after test -- --coverage
  - docker run satishrsdg/react-test npm test -- --coverage

after_success:
  - docker build -t satishrsdg/experiments:mathfunction-multi-client ./client
  - docker build -t satishrsdg/experiments:mathfunction-multi-nginx ./nginx
  - docker build -t satishrsdg/experiments:mathfunction-multi-server ./server
  - docker build -t satishrsdg/experiments:mathfunction-multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  #- docker login -u "$DOCKER_ID" -p "$DOCKER_PASS"
  # Take those images and push them to docker hub
  - docker push satishrsdg/experiments:mathfunction-multi-client
  - docker push satishrsdg/experiments:mathfunction-multi-nginx
  - docker push satishrsdg/experiments:mathfunction-multi-server
  - docker push satishrsdg/experiments:mathfunction-multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: math-function-nodejs
  env:  MathFunctionNodejs-env
  bucket_name: elasticbeanstalk-eu-west-2-231429439519
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET